[package]
name = "ward"
version = "0.1.0"
authors = ["ex0dus-0x <ex0dus@codemuch.tech>"]
description = "A security-hardened notary for Linux applications"

edition = "2018"

[dependencies]

clap = "2.33.*"
goblin = "0.2.3"
flate2 = "1.0.*"
microkv = "0.2.3"
